version: "3"

services:
   web:
     image: jekyll/jekyll
     container_name: davidederosa-web
     volumes:
       - .:/srv/jekyll
     command: jekyll serve --watch --force_polling --verbose -P 80
     environment:
       VIRTUAL_HOST: davidederosa.wtf
     expose:
       - 80
     restart: always

networks:
  default:
    name: nginx-proxy
